pull using ssh for jenkins

diff --git a/stackdriver/Makefile b/stackdriver/Makefile
--- a/stackdriver/Makefile
+++ b/stackdriver/Makefile
@@ -4,34 +4,34 @@ VERSION=5.3.0
 SHELL=/bin/bash
 
 source:
-	ifeq ($(PKGFORMAT),deb)
-		[ -d agent-deb ] || git clone https://github.com/Stackdriver/agent-deb.git
-		pushd agent-deb ; \
-		git pull ; \
-		popd
-	else ifeq ($(PKGFORMAT),rpm)
-		[ -d agent-rpm ] || git clone https://github.com/Stackdriver/agent-rpm.git
-		pushd agent-rpm ; \
-		git pull ; \
-		popd
-	else
-		echo "I don't know how to handle label '$(PKGFORMAT)'. Aborting build"
-		exit 1
-	endif
+ifeq ($(PKGFORMAT),deb)
+	[ -d agent-deb ] || git clone git@github.com:Stackdriver/agent-deb.git
+	pushd agent-deb ; \
+	git pull ; \
+	popd
+else ifeq ($(PKGFORMAT),rpm)
+	[ -d agent-rpm ] || git clone git@github.com:Stackdriver/agent-rpm.git
+	pushd agent-rpm ; \
+	git pull ; \
+	popd
+else
+	echo "I don't know how to handle label '$(PKGFORMAT)'. Aborting build"
+	exit 1
+endif
 
 build: source
-	ifeq ($(PKGFORMAT),deb)
-		pushd agent-deb ; \
-		make DISTRO="$(DISTRO)" ARCH="$(ARCH)" VERSION="$(VERSION)" BUILD_NUM="$(BUILD_NUM)" build ; \
-		popd
-	else ifeq ($(PKGFORMAT),rpm)
-		pushd agent-rpm ; \
-		make DISTRO="$(DISTRO)" ARCH="$(ARCH)" VERSION="$(VERSION)" BUILD_NUM="$(BUILD_NUM)" build ; \
-		popd
-	else
-	    echo "I don't know how to handle label '$(PKGFORMAT)'. Aborting build"
-		exit 1
-	endif
+ifeq ($(PKGFORMAT),deb)
+	pushd agent-deb ; \
+	make DISTRO="$(DISTRO)" ARCH="$(ARCH)" VERSION="$(VERSION)" BUILD_NUM="$(BUILD_NUM)" build ; \
+	popd
+else ifeq ($(PKGFORMAT),rpm)
+	pushd agent-rpm ; \
+	make DISTRO="$(DISTRO)" ARCH="$(ARCH)" VERSION="$(VERSION)" BUILD_NUM="$(BUILD_NUM)" build ; \
+	popd
+else
+	echo "I don't know how to handle label '$(PKGFORMAT)'. Aborting build"
+	exit 1
+endif
 
 clean:
 	rm -rf *.dsc *.deb *.tar.gz *.tar.bz2 agent-deb agent-rpm result apt *.rpm
